### ISSUE TITLE
Possible benchmark improvement

### ISSUE THREAD

**Issue by ignazio1977** [kracr/owl2bench#2]
https://github.com/kracr/owl2bench/blob/5670a1d83449f7c34afcc2899e3df6f8a1bd7ff0/Experiments/openllet/src/main/java/debug/openllet/Openllet.java#L27

Many reasoner implementations do quite a bit of work in the reasoner constructor, so it might be useful to measure the time used for this task as well.

**Comment by GunjanSingh1** [comment]
@ignazio1977 Thanks for the suggestion. I have updated the experiments.
